### ISSUE TITLE
3.0-777 not failing back to ipv4 for rrdp sessions for ripe/apnic anchors

### ISSUE THREAD

**Issue by cwiech** [RIPE-NCC/rpki-validator-3#70]
This version of code seems to be stuck using IPv6 only and won't fail back to ipv4 for apnic and ripe. It is unable to pull those anchors... and since (it appears) unless it has pulled all the defined anchors, the rtr portion of the code cannot proceed (even though it has the other anchors).

2019-02-01 17:46:45.836  WARN 8368 --- [eduler_Worker-4] n.r.r.r.a.v.RefreshCacheController       : validator http://localhost:8080/api/objects/validated not ready yet, will retry later

2019-02-01 17:43:20,292 	 WARN  	 quartzScheduler_Worker-7 			 n.r.r.v.r.RrdpService 		 Error retrieving RRDP repository at https://rrdp.ripe.net/notification.xml: Error downloading 'https://rrdp.ripe.net/notification.xml', cause: failed reading response stream for https://rrdp.ripe.net/notification.xml: java.util.concurrent.ExecutionException: java.net.SocketException: Could not connect to rrdp.ripe.net/2600:9000:2008:cc00:15:fa9:dc00:93a1:443, cause: java.net.SocketException: Could not connect to rrdp.ripe.net/2600:9000:2008:cc00:15:fa9:dc00:93a1:443, cause: Could not connect to rrdp.ripe.net/2600:9000:2008:cc00:15:fa9:dc00:93a1:443, cause: Network is unreachable
2019-02-01 17:44:20,073 	 WARN  	 quartzScheduler_Worker-4 			 n.r.r.v.r.RrdpService 		 Error retrieving RRDP repository at https://rrdp.apnic.net/notification.xml: Error downloading 'https://rrdp.apnic.net/notification.xml', cause: failed reading response stream for https://rrdp.apnic.net/notification.xml: java.util.concurrent.ExecutionException: java.net.SocketException: Could not connect to rrdp.apnic.net/2001:dd8:9:2:0:0:101:87:443, cause: java.net.SocketException: Could not connect to rrdp.apnic.net/2001:dd8:9:2:0:0:101:87:443, cause: Could not connect to rrdp.apnic.net/2001:dd8:9:2:0:0:101:87:443, cause: Network is unreachable

**Comment by cwiech** [comment]
FYI, this appears to only be a problem using an IPV4 proxy. Using the following seems to work for rsync, but not for rrdp.

export RSYNC_PROXY=localhost:8888
rpki.validator.http.proxy.port=8888

**Comment by nskalis** [comment]
same case here. 

1. using RSYNC_PROXY environment variable
2. forcing the IPv4 fallback by issuing

```
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1
```

the log messages complain about:

```
Sep 23 11:08:57 nlamsproape02 rpki-validator-3.sh[54022]: 2019-09-23 11:08:57,367          WARN           quartzScheduler_Worker-6                          n.r.r.v.r.RrdpServiceImpl                  Error retrieving RRDP repository at https://rrdp.apnic.net/notification.xml: Error downloading 'https://rrdp.apnic.net/notification.xml', cause: failed reading response stream for https://rrdp.apnic.net/notification.xml: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Connect Timeout, cause: java.net.SocketTimeoutException: Connect Timeout, cause: Connect Timeout
Sep 23 11:09:12 nlamsproape02 rpki-validator-3.sh[54022]: 2019-09-23 11:09:12,340          WARN           quartzScheduler_Worker-10                          n.r.r.v.r.RrdpServiceImpl                  Error retrieving RRDP repository at https://rrdp.ripe.net/notification.xml: Error downloading 'https://rrdp.ripe.net/notification.xml', cause: failed reading response stream for https://rrdp.ripe.net/notification.xml: java.util.concurrent.TimeoutException, cause: null
```

does that mean that the application does not honour the `RSYNC_PROXY` ?

**Comment by nskalis** [comment]
@cwiech did you figure it out ?

**Comment by cwiech** [comment]
No, I didn’t I reconfigured my lab server so that I didn’t have to use a proxy.

**Comment by geeohgeegeeoh** [comment]
I also have experienced this, OpenJDK on FreeBSD. I am considering moving this to a debian iohyve instance where I limit IPv6 binding, and keeping the nginx proxy on the underlying host.

it should be possible to control the IPv4 and IPv6 binding distinctly and manage this, Although obviously the underlying problem of failure to do IP protocol shift on connect timeout needs fixing.

I have moved to the RC build, hoping this is fixed. is there a ChangeLog somewhere we can track for issues?

**Comment by omuravskiy** [comment]
My quick search shows that the http client library that we are using does not have happy eyeballs implemented, and neither do other popular choices. This is not specific to Java version/distribution, so moving validator to another OS/distribution with non-working IPv6 will not help.
However, there are standalone implementations just for happy eyeballs, and it isn't difficult to implement one from scratch, so bare with us...

**Comment by lolepezy** [comment]
Hi all, 

@omuravskiy has implemented happy eyeballs, so that there's fallback between ipv6 and ipv4 addresses. You can try the release rpki-validator-3.1-2019.10.18_12.15.36 and see if it fixes the problem for you.

**Comment by lolepezy** [comment]
Please let us know if we still experience the problem. For now, I would consider it fixed and close the issue.
